exclude: ^tests/data/
repos:
  - repo: local
    hooks:
      - id: check-clean-notebook
        name: Clean notebooks
        language: python
        entry: clean-notebook
        files: '\.ipynb$'
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.991"
    hooks:
      - id: mypy
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.184"
    hooks:
      - id: ruff
