exclude: ^tests/data/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # frozen: v6.0.0
    hooks:
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-toml
      - id: check-yaml
      - id: check-json
      - id: check-executables-have-shebangs
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 0671d8ab202c4ac093b78433ae5baf74f3fc7246 # frozen: v0.15.15
    hooks:
      - id: ruff-check
      - id: ruff-format
  - repo: https://github.com/hoxbro/ty-pre-commit
    rev: 23cb3014e3d1e20b48267ad85c51168b692f29b5 # frozen: v0.0.40
    hooks:
      - id: ty-check
  - repo: https://github.com/codespell-project/codespell
    rev: 2ccb47ff45ad361a21071a7eedda4c37e6ae8c5a # frozen: v2.4.2
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli
  - repo: https://github.com/hoxbro/prettier-pre-commit
    rev: fb4fd26ea947350ec231580772317ec7261c8e21 # frozen: v3.8.3
    hooks:
      - id: prettier
        types_or:
          - markdown
          - yaml
  - repo: https://github.com/hoxbro/taplo-pre-commit
    rev: 605f960c3c571f814f535622a688bcde63ee87f6 # frozen: v0.9.3
    hooks:
      - id: taplo
        args:
          [
            --option,
            align_comments=false,
            --option,
            column_width=100,
            --option,
            "indent_string=    ",
          ]
