[build-system]
requires = ["setuptools", "wheel", "setuptools-git-versioning"]
build-backend = "setuptools.build_meta"

[project]
name = "clean_notebook"
description = "A simple package to clean notebook files output and metadata"
requires-python = ">=3.8"
keywords = ["clean", "notebook"]
license = {text = "BSD 3-Clause License"}
dynamic = ["version"]

[project.scripts]
clean-notebook = "clean_notebook.__main__:main"

[project.optional-dependencies]
dev = [
  "pytest",
  "black",
  "isort",
  "pre-commit"
]

[tool.setuptools.packages.find]
where = ["src"]
include = ["clean_notebook*"]
namespaces = false

[tool.setuptools-git-versioning]
enabled = true
dev_template = "{tag}+{ccount}.g{sha}"
dirty_template = "{tag}+{ccount}.g{sha}.dirty"

[tool.pytest.ini_options]
addopts = "-v"

[tool.black]
line-length = 88
target-version = ['py37', 'py38', 'py39', 'py310']
include = '\.pyi?$'

[tool.isort]
atomic = true
profile = "black"
line_length = 88
skip_gitignore = true
known_first_party = ["clean_notebook"]
