name: build and release

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - '*'
  workflow_dispatch:
  release:
    types:
    - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build sdist and wheel
      run: pipx run nox -s build

    - uses: actions/upload-artifact@v3
      with:
        path: dist/*

  publish:
    needs: [dist]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'

    steps:
    - uses: actions/download-artifact@v3
      with:
        name: artifact
        path: dist

    - uses: pypa/gh-action-pypi-publish@v1.6.4
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}
