name: Build and Publish

on:
  workflow_dispatch:
  pull_request:
  release:
    types:
    - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Build sdist and wheel
      run: pipx run nox -s build
    - uses: pypa/gh-action-pypi-publish@v1.6.4
      if: github.event_name == 'release' && github.event.action == 'published'
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}
